[package]
name = "bevy_bistro_playground"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies.bevy]
version = "0.9.0"
default-features = false
features = [ "bevy_core_pipeline", "bevy_render", "bevy_pbr", "bevy_asset", "bevy_gltf", "bevy_winit", "bevy_scene", "png" ]
